export const countries = [
    { name: 'India', code: 'in', flag: 'https://flagcdn.com/16x12/in.png' },
    {
        name: 'United States',
        code: 'us',
        flag: 'https://flagcdn.com/16x12/us.png',
    },
    { name: 'Canada', code: 'ca', flag: 'https://flagcdn.com/16x12/ca.png' },
    {
        name: 'United Kingdom',
        code: 'gb',
        flag: 'https://flagcdn.com/16x12/gb.png',
    },
    { name: 'Australia', code: 'au', flag: 'https://flagcdn.com/16x12/au.png' },
    { name: 'Singapore', code: 'sg', flag: 'https://flagcdn.com/16x12/sg.png' },
    { name: 'Malaysia', code: 'my', flag: 'https://flagcdn.com/16x12/my.png' },
    { name: 'Philippines', code: 'ph', flag: 'https://flagcdn.com/16x12/ph.png' },
    { name: 'Indonesia', code: 'id', flag: 'https://flagcdn.com/16x12/id.png' },
    {
        name: 'United Arab Emirates',
        code: 'ae',
        flag: 'https://flagcdn.com/16x12/ae.png',
    },
    {
        name: 'Saudi Arabia',
        code: 'sa',
        flag: 'https://flagcdn.com/16x12/sa.png',
    },
    { name: 'Qatar', code: 'qa', flag: 'https://flagcdn.com/16x12/qa.png' },
    { name: 'Kuwait', code: 'kw', flag: 'https://flagcdn.com/16x12/kw.png' },
    { name: 'Oman', code: 'om', flag: 'https://flagcdn.com/16x12/om.png' },
    { name: 'Bahrain', code: 'bh', flag: 'https://flagcdn.com/16x12/bh.png' },
    { name: 'Germany', code: 'de', flag: 'https://flagcdn.com/16x12/de.png' },
    { name: 'France', code: 'fr', flag: 'https://flagcdn.com/16x12/fr.png' },
    { name: 'China', code: 'cn', flag: 'https://flagcdn.com/16x12/cn.png' },
    { name: 'Japan', code: 'jp', flag: 'https://flagcdn.com/16x12/jp.png' },
    { name: 'South Korea', code: 'kr', flag: 'https://flagcdn.com/16x12/kr.png' },
    { name: 'Russia', code: 'ru', flag: 'https://flagcdn.com/16x12/ru.png' },
    { name: 'Brazil', code: 'br', flag: 'https://flagcdn.com/16x12/br.png' },
    { name: 'Mexico', code: 'mx', flag: 'https://flagcdn.com/16x12/mx.png' },
    { name: 'Argentina', code: 'ar', flag: 'https://flagcdn.com/16x12/ar.png' },
    { name: 'Spain', code: 'es', flag: 'https://flagcdn.com/16x12/es.png' },
    { name: 'Italy', code: 'it', flag: 'https://flagcdn.com/16x12/it.png' },
    { name: 'Netherlands', code: 'nl', flag: 'https://flagcdn.com/16x12/nl.png' },
    { name: 'Switzerland', code: 'ch', flag: 'https://flagcdn.com/16x12/ch.png' },
    { name: 'Sweden', code: 'se', flag: 'https://flagcdn.com/16x12/se.png' },
    { name: 'Norway', code: 'no', flag: 'https://flagcdn.com/16x12/no.png' },
    { name: 'Denmark', code: 'dk', flag: 'https://flagcdn.com/16x12/dk.png' },
    { name: 'Finland', code: 'fi', flag: 'https://flagcdn.com/16x12/fi.png' },
    { name: 'Greece', code: 'gr', flag: 'https://flagcdn.com/16x12/gr.png' },
    { name: 'Turkey', code: 'tr', flag: 'https://flagcdn.com/16x12/tr.png' },
    { name: 'Egypt', code: 'eg', flag: 'https://flagcdn.com/16x12/eg.png' },
    {
        name: 'South Africa',
        code: 'za',
        flag: 'https://flagcdn.com/16x12/za.png',
    },
    { name: 'Nigeria', code: 'ng', flag: 'https://flagcdn.com/16x12/ng.png' },
    { name: 'Kenya', code: 'ke', flag: 'https://flagcdn.com/16x12/ke.png' },
    { name: 'Ghana', code: 'gh', flag: 'https://flagcdn.com/16x12/gh.png' },
    { name: 'Morocco', code: 'ma', flag: 'https://flagcdn.com/16x12/ma.png' },
    { name: 'Tunisia', code: 'tn', flag: 'https://flagcdn.com/16x12/tn.png' },
    { name: 'Algeria', code: 'dz', flag: 'https://flagcdn.com/16x12/dz.png' },
    { name: 'Tanzania', code: 'tz', flag: 'https://flagcdn.com/16x12/tz.png' },
    { name: 'Uganda', code: 'ug', flag: 'https://flagcdn.com/16x12/ug.png' },
    { name: 'Zambia', code: 'zm', flag: 'https://flagcdn.com/16x12/zm.png' },
    { name: 'Zimbabwe', code: 'zw', flag: 'https://flagcdn.com/16x12/zw.png' },
    { name: 'Ethiopia', code: 'et', flag: 'https://flagcdn.com/16x12/et.png' },
    { name: 'Sudan', code: 'sd', flag: 'https://flagcdn.com/16x12/sd.png' },
    { name: 'Libya', code: 'ly', flag: 'https://flagcdn.com/16x12/ly.png' },
    { name: 'Iraq', code: 'iq', flag: 'https://flagcdn.com/16x12/iq.png' },
    { name: 'Iran', code: 'ir', flag: 'https://flagcdn.com/16x12/ir.png' },
    { name: 'Pakistan', code: 'pk', flag: 'https://flagcdn.com/16x12/pk.png' },
    { name: 'Afghanistan', code: 'af', flag: 'https://flagcdn.com/16x12/af.png' },
    { name: 'Bangladesh', code: 'bd', flag: 'https://flagcdn.com/16x12/bd.png' },
    { name: 'Sri Lanka', code: 'lk', flag: 'https://flagcdn.com/16x12/lk.png' },
    { name: 'Nepal', code: 'np', flag: 'https://flagcdn.com/16x12/np.png' },
    { name: 'Bhutan', code: 'bt', flag: 'https://flagcdn.com/16x12/bt.png' },
    { name: 'Maldives', code: 'mv', flag: 'https://flagcdn.com/16x12/mv.png' },
    { name: 'New Zealand', code: 'nz', flag: 'https://flagcdn.com/16x12/nz.png' },
    { name: 'Fiji', code: 'fj', flag: 'https://flagcdn.com/16x12/fj.png' },
    {
        name: 'Papua New Guinea',
        code: 'pg',
        flag: 'https://flagcdn.com/16x12/pg.png',
    },
    {
        name: 'Solomon Islands',
        code: 'sb',
        flag: 'https://flagcdn.com/16x12/sb.png',
    },
    { name: 'Vanuatu', code: 'vu', flag: 'https://flagcdn.com/16x12/vu.png' },
    { name: 'Samoa', code: 'ws', flag: 'https://flagcdn.com/16x12/ws.png' },
    { name: 'Tonga', code: 'to', flag: 'https://flagcdn.com/16x12/to.png' },
    { name: 'Kiribati', code: 'ki', flag: 'https://flagcdn.com/16x12/ki.png' },
    { name: 'Tuvalu', code: 'tv', flag: 'https://flagcdn.com/16x12/tv.png' },
    { name: 'Nauru', code: 'nr', flag: 'https://flagcdn.com/16x12/nr.png' },
    {
        name: 'Marshall Islands',
        code: 'mh',
        flag: 'https://flagcdn.com/16x12/mh.png',
    },
    { name: 'Micronesia', code: 'fm', flag: 'https://flagcdn.com/16x12/fm.png' },
    { name: 'Palau', code: 'pw', flag: 'https://flagcdn.com/16x12/pw.png' },
    {
        name: 'Cook Islands',
        code: 'ck',
        flag: 'https://flagcdn.com/16x12/ck.png',
    },
    { name: 'Niue', code: 'nu', flag: 'https://flagcdn.com/16x12/nu.png' },
    { name: 'Tokelau', code: 'tk', flag: 'https://flagcdn.com/16x12/tk.png' },
    {
        name: 'Norfolk Island',
        code: 'nf',
        flag: 'https://flagcdn.com/16x12/nf.png',
    },
    {
        name: 'Christmas Island',
        code: 'cx',
        flag: 'https://flagcdn.com/16x12/cx.png',
    },
    {
        name: 'Cocos Islands',
        code: 'cc',
        flag: 'https://flagcdn.com/16x12/cc.png',
    },
    {
        name: 'Pitcairn Islands',
        code: 'pn',
        flag: 'https://flagcdn.com/16x12/pn.png',
    },
    {
        name: 'Falkland Islands',
        code: 'fk',
        flag: 'https://flagcdn.com/16x12/fk.png',
    },
    {
        name: 'Saint Helena',
        code: 'sh',
        flag: 'https://flagcdn.com/16x12/sh.png',
    },
    {
        name: 'British Indian Ocean Territory',
        code: 'io',
        flag: 'https://flagcdn.com/16x12/io.png',
    },
    { name: 'Guernsey', code: 'gg', flag: 'https://flagcdn.com/16x12/gg.png' },
    { name: 'Jersey', code: 'je', flag: 'https://flagcdn.com/16x12/je.png' },
];
